a = 5
print ("Addizione con +")
print (a + 4)
print ("Sottrazione con -")
print (a - 4)
print ("Motiplicazione con *")
print (a * 4)
print ("Divisione con /")
print (a / 4)
print ("Divisione con restituzione del solo intero //")
print (a // 4)
print ("Elevazione a potenza con **")
print (a ** 4)
print ("Resto della divisione con %")
print (a % 4)
